spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/lihu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true